auto_sync = true
ctrl_n_shortcuts = true
filter_mode = "workspace"
search_mode = "fuzzy"
sync_address = "https://atuin.ishioni.casa"
update_check = false
workspaces = true
history_filter = [
    "^cd",
    "^chezmoi",
    "^cm",
    "^git",
    "^gst$",
    "^jj",
    "^ll",
    "^ls",
    "^x$",
]

[sync]
records = true